#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --dpi 81 &
#~/.fehbg &
picom &
xset m 0 0 &
#xinput --set-prop 8 "libinput Accel Speed" -0.7 &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width        3
bspc config window_gap          16
bspc config top_padding 	16
bspc config border_radius	10

bspc config split_ratio         0.6

bspc config normal_border_color '#1c1c1c'
bspc config active_border_color '#1c1c1c'
bspc config focused_border_color '#1c1c1c'

# bspc rule -a kitty state=floating
bspc rule -a lxappearance state=floating
bspc rule -a spotify state=floating
